# HWW

base_path: "root://eosuser.cern.ch//eos/user/r/rband/HVV2LRDF/merged_2lep_1FJ_r2_2lep_1FJ_20260615211230_2lep_1FJ/"

training_features:
  - lepton_pt: log
  - lepton_eta: minmax
  - lepton_phi: minmax
  - lepton_mass: log
  - met_phi: minmax
  - met_pt: log
  - fatjet_pt: log
  - fatjet_eta: minmax
  - fatjet_phi: minmax
  - fatjet_mass: log
  - fatjet_tau2: none
  - fatjet_tau1: none

split_features: ["lepton_"]

derived_vars: {}

extra_vars:
  - weight
  - fatjet_globalParT3_Xbb
  - fatjet_globalParT3_QCD

constraint_var: "vbs_score"

preselection: "((fatjet_globalParT3_Xbb/(fatjet_globalParT3_Xbb+fatjet_globalParT3_QCD)) >= 0.1)" # Hbb tag score, need to work on optimal cut

learning_rate: 0.0001
batch_size: 4096
n_epochs: 1000

architecture: [64, 32, 16]
bce_weight: 1.0
disco_lambda: 10.0

closure_n_events_min: 10
closure_symmetrize: true
use_batchnorm: true
dropout: 0.2
weight_decay: 0.01
label_smoothing: 0.0

devices: [0]

output: "run2_2L_1FJ"