# HWW

base_path: "root://eosuser.cern.ch//eos/user/r/rband/HVV2LRDF/merged_2lep_1FJ_r3_2lep_1FJ_20260615211529_2lep_1FJ/"

training_features:
  - lepton_pt: log
  - lepton_eta: minmax
  - lepton_phi: minmax
  - lepton_mass: log
  - met_phi: minmax
  - met_pt: log
  - fatjet_pt: log
  - fatjet_eta: minmax
  - fatjet_phi: minmax
  - fatjet_mass: log
  - fatjet_tau2: none
  - fatjet_tau1: none

split_features: ["lepton_"]

derived_vars: {}
auto_include_derived_vars: false
auto_include_derived_vars_transform: none

extra_vars:
  - weight
  # - boosted_h_candidate_score
  # - boosted_v_candidate_score
  - fatjet_globalParT3_Xbb
  - fatjet_globalParT3_QCD
  - vbs_detajj

constraint_var: "vbs_score"

# preselection: "(boosted_h_candidate_score >= 0.1) & (boosted_v_candidate_score >= 0.1)"
preselection: "((fatjet_globalParT3_Xbb/(fatjet_globalParT3_Xbb+fatjet_globalParT3_QCD)) >= 0.1)"

learning_rate: 0.0001
batch_size: 2048
n_epochs: 1000

architecture: [64, 32, 16]
bce_weight: 1.0
disco_lambda: 5.0

use_batchnorm: true
dropout: 0.2
weight_decay: 0.01
label_smoothing: 0.0

devices: [1]

output: "run3_2L_1FJ"